### PR TITLE
Add Jinja2 'do' extension

### PR DESCRIPTION
**Pull request by n-rodriguez**

### CODE REVIEW

**Comment by bbinet** [comment]
Have you verified that it actually fix your #25 issue?

**Comment by n-rodriguez** [comment]
Yes. I'm using [Test Kitchen](https://github.com/test-kitchen/test-kitchen) and it works.

**Comment by n-rodriguez** [comment]
Jinja2 doc : http://jinja.pocoo.org/docs/2.9/extensions/

**Comment by bbinet** [comment]
Cool, thanks!

**Comment by n-rodriguez** [comment]
Thank you!

**Pull request merged**
