### PR TITLE
allow yaml files to reference previous values

### PR DESCRIPTION
**Pull request by robnagler**
### What does this PR do?

Enables previously parsed pillar.stack YAML file values to be referenced by subsequent YAML files.
### What issues does this PR fix or reference?

One of the features of pillar.stack is that it allows you to reference pillars in a pillar. This fix allows you to reference pillars as well as the pillar values of previous files in the pillar.stack. 

There is one caveat: you can only do this if you have not defined any other pillar values before pillar.stack executes. This means that pillar/top.sls is empty. This feature is useful if you switch all your pillar config to pillar.stack. 

The reason this restriction is in place is that in order to merge previously defined, non-pillar.stack values, you have to use the salt merging strategy that would be in place once pillar.stack returns its values. This behavior is tricky to replicate, and it conflicts with the code that merges the pillar stack strategies. If there are no previously defined pillar values, then there is no merging necessary before pillar.stack executes in a semantically consistent manner.
### Tests written?

No.

### CODE REVIEW

**Comment by bbinet** [comment]
Hum, I'm not sure I understand correctly, but I think what you're trying to achieve is already supported by using the `stack` object directly in the jinja templates.
See https://github.com/bbinet/pillarstack/blob/master/stack.py#L52 and https://github.com/bbinet/pillarstack/blob/master/stack.py#L54 we pass the `stack=stack` argument to the `render` function which means we can use the `stack` object directly in our templates.

Does it match what you were trying to do?

**Comment by robnagler** [comment]
I see now. Wasn't obvious to me. Maybe need to include in the examples?

It would be nice to not have to think in two contextual terms:
- In the YAML files, refer to "stack"
- In state files, refer to "pillar"

What's worse in our case is there are 
[raw jinja templates as "pillar_contents"](https://github.com/radiasoft/salt-conf/blob/8c5411346bb164486923cfb6f3c772abab39bad2/srv/pillar/jupyterhub/base.yml#L26)
so in one file there would be references to the same variable in two different ways:

``` jinja2
{% raw %}
foo: {{ pillar.bar }}
{% endraw %}
baz: {{ stack.bar }}
```

While this encoding is fast fail, it's not ideal imo. 

Your approach is cleaner from a merging perspective, however, so there's a tradeoff. Obviously, it's up to you. :)

**Comment by robnagler** [comment]
One thought, maybe use the term "pillar_stack" instead of "stack"? And, perhaps include such a reference in the examples?

**Comment by bbinet** [comment]
I understand your concerns, but I think I prefer to stick with the `stack` naming rather than using `pillar` because it is more explicit, and I think it helps the user better understand that the `stack` variable will not necessarily have the same value in all yaml files because the `stack` is the current state of the yaml data being built (stacked) to create pillar data in the end.

I hope it makes sense to you.
But I would be happy to merge a pull request with some clarifications or examples in the readme if you think it could be improved.

**Pull request closed without merging**
